id = "flux-language"
name = "Flux Language"
version = "0.0.1"
schema_version = 1
authors = ["Flux Contributors"]
description = "Flux language support (.flx) for Zed"
repository = "https://github.com/sger/flux"
